# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pulse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'JTAppleCalendar', '~> 7.1'
  # Pods for Pulse

end
